### PR TITLE
Simplified the error check

### LINKED ISSUE #92: The check for remote hangups is too strict
Apparently, on some git versions or OS locales, this error is printed out a bit differently:

```
 #  @ckeditor/ckeditor5-upload                                           39/39 (100%)
Cloning into '/Users/pjasiun/workspace/ckeditor5/packages/ckeditor5-upload'...
remote: Enumerating objects: 5, done.
remote: Counting objects: 100% (5/5), done.
remote: Compressing objects: 100% (5/5), done.
packet_write_wait: Connection to 192.30.253.113 port 22: Broken pipe
fatal: the remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
```

The current check expects `fatal: The remote...` and that does not match.

I think that this check is in general too complicated. `/fatal: the remote end hung up unexpectedly/i` should be enough. After all, nothing bad should happen if we have false positive anyway.

### PR DESCRIPTION
**Pull request by pomek**
### Suggested merge commit message ([convention](https://github.com/ckeditor/ckeditor5-design/wiki/Git-commit-message-convention))

Fix: Simplified a check for "remote end hung up" error during the `bootstrap` command. Closes #92.

### CODE REVIEW

**Comment by pomek** [comment]
> Missing a test.

I did it on purpose because this test has no value. If the previous one (that uses capital letters) passes, next one with small letters will pass as well. And on the occasion, we increased tests execution time by 5 secs. Missing test has been added.

**Comment by Reinmar** [comment]
> If the previous one (that uses capital letters) passes, next one with small letters will pass as well.

Somehow, the bug was there. So the previous implementation was missing this case. Therefore, it deserves a test that fails if we somehow revert/break this in the future again.

**Comment by Reinmar** [comment]
cc @pjasiun could you retest?

**Comment by pjasiun** [comment]
Works 🎆

**Pull request merged**
