### PR TITLE
T/55: Mgit status should highlight all non-master rows

### LINKED ISSUE #55: Mgit status should highlight all non-master rows
ATM mgit highlights only the branches which:
* are different than the entry in the `mgit.json`, 
* have unstaged files.

My point is that this pink color should help developers to focus on what belongs to the branch constellation and what does not. The most common case is that `mgit.json` is already configured.

image

### PR DESCRIPTION
**Pull request by pomek**
### Suggested merge commit message ([convention](https://github.com/ckeditor/ckeditor5-design/wiki/Git-commit-message-convention))

Other: Improved UI of the displayed table with statuses with repositories. Closes #55.

* If current branch is other than specified in `mgit.json` – the branch will be prefixed with `!`,
* If current branch is other than `master` – the whole row will be highlighted (in pink).

### CODE REVIEW

**Comment by Reinmar** [comment]
I think that I'd rather see the "!" after the branch name to not distort the alignment:

image

Also, we should think about better (shorter) wording for the legend. 

Also: "Collecting statuses from all found packages..." could become a simple "Collecting package statuses...".

**Comment by Reinmar** [comment]
WDYT @oleq?

**Comment by pomek** [comment]
After a branch name, we have a note about pull/push with the remote. This is the reason why I use the prefix instead of the suffix.

> Also, we should think about better (shorter) wording for the legend.

👍 

> Also: "Collecting statuses from all found packages..." could become a simple "Collecting package statuses...".

👍

**Comment by Reinmar** [comment]
> After a branch name, we have a note about pull/push with the remote. This is the reason why I use the prefix instead of the suffix.

Good point. So let's leave it like you proposed it.

I'll change the legend a bit and merge this.

**Pull request merged**
